kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-data
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Reclaim
  resources:
    requests:
      storage: 8Gi
