apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-minio
  namespace: {{.RC_NAMESPACE}}
  labels:
    heritage: deis
    release: 2.0.0-beta
spec:
  replicas: 1
  selector:
    app: deis-minio
  template:
    metadata:
      labels:
        app: deis-minio
    spec:
      containers:
        - name: deis-minio
          image: {{.RC_IMAGE}}
          imagePullPolicy: Always
          env:
            - name: HEALTH_SERVER_PORT
              value: "8082"
          ports:
            - containerPort: 9000
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8092
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8092
            initialDelaySeconds: 30
            timeoutSeconds: 1
          command:
            - boot
          args:
            # not running with ssl yet
            # - "--cert=/var/run/secrets/deis/minio/ssl/access-cert"
            # - "--key=/var/run/secrets/deis/minio/ssl/access-pem"
            - "server"
            - "/home/minio/"
          volumeMounts:
            - name: minio-admin
              mountPath: /var/run/secrets/deis/minio/admin
              readOnly: true
            - name: minio-user
              mountPath: /var/run/secrets/deis/minio/user
              readOnly: true
            # - name: minio-ssl
            #   mountPath: /var/run/secrets/deis/minio/ssl
            #   readOnly: true
      volumes:
        - name: minio-admin
          secret:
            secretName: minio-admin
        - name: minio-user
          secret:
            secretName: minio-user
        # - name: minio-ssl
        #   secret:
        #     secretName: minio-ssl
