apiVersion: v1
kind: Service
metadata:
  # Give this a useful name.
  name: deis-minio
  labels:
    heritage: deis
    release: 0.0.0
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 32760
      targetPort: 9000
      name: s3
      protocol: TCP
  selector:
    # Match the selector in the RC
    app: deis-minio
