apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: {{.SECRET_NAMESPACE}}
  heritage: deis
type: Opaque
data:
  access-key-id: OFRaUlkySlJXTVBUNlVNWFI2STUK
  access-secret-key: Z2JzdHJPdm90TU1jZzJzTWZHVWhBNWE2RXQvRUk1QUx0SUhzb2JZawo=
